openapi: 3.0.0
info:
  title: Top Trumps API
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /decks:
    get:
      operationId: findAll
      summary: Returns a list of decks.
      responses:
        '200':
          description: An array of decks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Deck'
    post:
      operationId: create
      summary: create a new deck
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Deck'
      responses:
        '201':
          description: Created deck
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deck'
  /decks/{id}:
    get:
      operationId: find
      summary: find a deck
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: deck
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deck'
    patch:
      operationId: update
      summary: update a deck
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Deck'
      responses:
        '200':
          description: Updated deck
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deck'
    delete:
      operationId: delete
      summary: delete a deck
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '204':
          description: deleted deck
components:
  schemas:
    Deck:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        imageUrl:
          type: string
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/AttributeType'
        cards:
          type: array
          items:
            $ref: '#/components/schemas/Card'
    Card:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        imageUrl:
          type: string
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
    Attribute:
      type: object
      properties:
        type:
          type: string
        value:
          type: number
          format: float
    AttributeType:
      type: object
      properties:
        name:
          type: string
        units:
          type: string
